$schema: https://raw.githubusercontent.com/remal-github-actions/sync-with-template/main/local-transformations.schema.json

repositories:
- remal-github-actions/template-typescript

transformations:
- name: .gitattributes
  format: text
  includes:
  - .gitattributes
  script: |
    return content
        + [
            '',
            '# Remal GitHub actions:',
            '/dist/** -diff linguist-generated=true',
            '',
        ].join('\n')
- name: .gitignore
  format: text
  includes:
  - .gitignore
  script: |
    return content
        + [
            '',
            '# Remal GitHub actions:',
            '/.pnp.*',
            '/.yarn/*',
            '!/.yarn/patches/',
            '!/.yarn/plugins/',
            '!/.yarn/releases/',
            '!/.yarn/sdks/',
            '!/.yarn/versions/',
            '/build',
            '/coverage',
            '/dist/build',
            '/dist/*.index.js',
            '',
        ].join('\n')
- name: .github/sync-with-template.yml
  format: yaml
  includes:
  - .github/sync-with-template.yml
  script: |
    content.includes = content.includes ?? []
    ;[
      'check-dependency-engines.*js',
      'update-node-version-in-files.*js',
      'tsconfig-generate-app.*js',
      '.releaseignore',
    ].forEach(path => {
      if (!content.includes.includes(path)) {
        content.includes.push(path)
      }
    })
    content.excludes = content.excludes ?? []
    ;[
      '.github/workflows/release-drafter.yml',
      '.github/release-drafter.yml',
    ].forEach(path => {
      if (!content.excludes.includes(path)) {
        content.excludes.push(path)
      }
    })
    return content
- name: .github/workflows/codespell.yml
  format: text
  includes:
  - .github/workflows/codespell.yml
  script: |
    return content
      .replace(/((\n[ ]+)check_hidden: '[^']*')/, "$1$2skip: './.git/**,./.yarn/**,./node_modules/**,./build/**,./dist/**,./coverage/**'")
- name: Renovate
  format: text
  includes:
  - .github/renovate.json5
  replaceWithText: |
    {
      $schema: "https://docs.renovatebot.com/renovate-schema.json",
      extends: ["github>remal/renovate-config:global"],

      "git-submodules": {
        enabled: false, // This is in beta for now, so let's use Dependabot to update Git submodules
      },

      constraintsFiltering: "strict",
      // $$$sync-with-template-modifiable: constraints $$$
      // $$$sync-with-template-modifiable-end$$$

      packageRules: [
        {
          matchCategories: ["node"],
          enabled: false,
        },
        {
          matchCategories: ["js"],
          matchPackageNames: ["@types/node", "@tsconfig/node**"],
          matchUpdateTypes: ["major", "replacement"],
          enabled: false,
        },
        {
          matchCategories: ["js"],
          matchPackageNames: ["renovate"],
          schedule: ["* 15-23 * * 6"]
        },
      ],
    }
