configDependencies:
  '@pnpm/types-fixer': 0.1.0+sha512-h8iYCPyf0FrMH/pyu3EYryOaGUEI8NsQxsCcdp+XO9sYqUr9jw3ARTEv0Ifl4WHhoLhdxud2zwto1Y9WuOT3QA==
  '@pnpm/trusted-deps': 0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ==

engineStrict: true

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json

pnpmfile: node_modules/.pnpm-config/@pnpm/types-fixer/pnpmfile.cjs

savePrefix: ''

shamefullyHoist: true

updateNotifier: false
